pipeline:
    publish:
        image: plugins/docker
        repo: registry.stuifzandapp.com/microsub-server
        registry: registry.stuifzandapp.com
        secrets: [ docker_username, docker_password ]

    deploy:
        image: appleboy/drone-ssh
        host: microsub.stuifzandapp.com
        username: microsub
        secrets: ['ssh_key']
        script:
            - cd /home/microsub/microsub
            - docker-compose pull web
            - docker-compose up -d

    notify:
        image: plugins/webhook
        settings:
            debug: true
        secrets:
            - source: success_webhook
              target: urls
        when:
            status: [success]

    notify_failure:
        image: plugins/webhook
        settings:
            debug: true
        secrets:
            - source: failure_webhook
              target: urls
        when: 
            status: [failure]
