pipeline:
    build:
        image: golang
        commands:
            - go get github.com/pstuifzand/microsub-server/...
            - go build github.com/pstuifzand/microsub-server/cmd/eksterd

    publish:
        image: plugins/docker
        repo: registry.stuifzandapp.com/microsub-server
        registry: registry.stuifzandapp.com
        secrets: [ docker_username, docker_password ]

    deploy:
        image: appleboy/drone-ssh
        host: microsub.stuifzandapp.com
        username: microsub
        secrets: ['ssh_key']
        script:
            - cd /home/microsub/microsub
            - docker-compose pull web
            - docker-compose up -d
